source 'https://rubygems.org'
gem 'rails', '4.2.5.1'
gem 'acts_as_votable', '~> 0.10.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'aws-sdk', '< 2.0'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'devise', '~> 3.5', '>= 3.5.6'
gem 'simple_form', '~> 3.2', '>= 3.2.1'
gem 'paperclip', '~> 4.3', '>= 4.3.6'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
group :development, :test do
   gem 'byebug'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'sqlite3'
end
group :production do
 gem 'pg'
 gem 'rails_12factor'
end
